### ISSUE TITLE
Various occasional 500, 502, 504 errors in running and accessing simulation runs and validating models

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3811]
I'm working through testing the latest production version. Here are what appear to be deployment-related issues that I've encountered.

## Issues
- [ ] 2 502 errors in submitting simulation runs for 86 BiGG models (prod)
    No insight here; this is further back than the Argo log for the API tracks
- [ ] 1 transient 500 error in retrieving simulation results 61b99352a73ffdd52158c96d (prod) of 37 runs
    Relevant portion of Argo log for HSDS
    ```
    REQ> GET: /datasets [/results/61b99352a73ffdd52158c96d]
    REQ> GET: / [/results/61b99352a73ffdd52158c96d]
    REQ> GET: /groups/g-e6c40390-35689774-6e4c-8b18bd-e01ffc [/results/61b99352a73ffdd52158c96d]
    ERROR> request to http://10.20.3.133:6101/groups/g-e6c40390-35689774-6e4c-8b18bd-e01ffc/links failed with code: 500
    ```
    Accessing the results later succeeded
- [ ] 1 x 502 and 1 x 504 error accessing https://combine.api.biosimulations.org/model/validate with an RBA model of validating ~10 models

We're always going to have some errors. But this rate of error seems a bit high.

## Potential solution
Seems to me we need to assign more resources because these errors appear to come from the deployment rather than the logic of our code.

@bilalshaikh42 thoughts?

**Comment by jonrkarr** [comment]
The prod dispatch service also seems to be taking a long time to process runs.

**Comment by jonrkarr** [comment]
Likely related to the crashed containers

**Comment by jonrkarr** [comment]
The rate of 500/502 errors in submitting BiGG to the API is now much higher

**Comment by jonrkarr** [comment]
Gateway errors occurred again today (12/20) in submitting runs to https://api.biosimulations.org

**Comment by jonrkarr** [comment]
@bilalshaikh42 please try increasing the allocated resources. Presently it is challenging to get through 88 simulation runs for BiGG (submitted sequentially with ~15 second delay in between) without the API, COMBINE API, dispatch service, and simulators API pods each crashing.

**Comment by bilalshaikh42** [comment]
Yes, I have been getting notifications about high memory utilization. Let me tweak the resources.

**Comment by bilalshaikh42** [comment]
For reference:

Stackdriver Incident

Memory allocatable utilization for biosimulations gke-biosimulations-nap-e2-medium-18q6-d8445605-o55h with metric labels {component=pods, memory_type=non-evictable} is above the threshold of 0.900.
https://app.google.stackdriver.com/incidents/0.mb2fjofpn280?project=biosimulations&src=VESPA

**Comment by bilalshaikh42** [comment]
Steps taken: 
1. I have increased the memory requests for the combine-api and dispatch-service.
2.  I don't believe that the API or simulators-api were having any issues with memory limits, but were going down due to node memory being used by the others. I increased the memory limits for the API. 
3. Increased the maximum amount of nodes that can automatically be provisioned by GKE when it detects memory utilization is high 
4. Set up affinity and anti-affinity rules to keep the pods deployed in groups that include the api, dispatch-service, and combine-api, but keep these groups on separate nodes. 

Further steps to try: 
- increase the size of the nodes rather than adding more nodes 
-

**Comment by jonrkarr** [comment]
Please test the configuration by submitting 100 jobs.

**Comment by jonrkarr** [comment]
BiGG test (2021-12-22 4:30pm)
- New configuration made it through 48 BiGG projects before one failed with 500 error (after 1 retry after 0.1s)
- All submitted runs executed successfully
- 3 runs didn't successfully publish -- status were still processing when publication was attempted; filed as #3885 and addressed in #3886
  - `iBWG_1329`: `61c3998cb5d9e03c1d4cb6fe`
  - `iECH74115_1262`: `61c39a3cae7a689764d904a3`
  - `iECS88_1305`: `61c39ac0ae7a689764d90668`
- Internally, there were 14 502 errors for posting files, log, metadata, specifications,

Conclusion: 
- Substantially improved
- However, looks like more resources are still needed

**Comment by jonrkarr** [comment]
@bilalshaikh42 please try increasing the size of the nodes. It looks like we're using `e2-medium`. It looks like the next size up is `e2-standard-2`

**Comment by jonrkarr** [comment]
I increased the number of replicas for the API and their requested memory and re-tested. I saw a similar number of 502 errors (dispatch-service can't reach API). This time, my test failed with a 504 error (unable to reach API).

**Comment by jonrkarr** [comment]
Ran another test, with more generous client-side (my machine submitting runs) retrying. 
- Internally, the dispatch-service reported at least 47 502 errors. Nearly all of these could be retried.
- 1 job (61c426fe1c93f90892dfb8e7) failed with saving specifications and metadata.
- 1 job (61c427dd6d7cb516694e406c) failed with 409 conflict in hsload in the SBATCH job. This is an h5pyd/hsds error. I think this is exacerbated by our HSDS service running out of resources and partially saving results.
- 1 run request was rejected because COMBINE archive could not be stored withing 30 s allotted time out

**Comment by bilalshaikh42** [comment]
> @bilalshaikh42 please try increasing the size of the nodes. It looks like we're using `e2-medium`. It looks like the next size up is `e2-standard-2`

I edited the node pool to use high-memory nodes. Each node should now have 16gb of memory, which might help with the issues that we are seeing with the hsds and dispatch-service

**Comment by jonrkarr** [comment]
Do the container limits also need to be raised?
- Maximum memory
- Maximum CPU

**Comment by bilalshaikh42** [comment]
I don't think the maximum cpu is posing any issues. With more  memory on the nodes, raising the maximum memory limits may be helpful

**Comment by jonrkarr** [comment]
I increased the maxima

**Comment by jonrkarr** [comment]
I ran BiGG again with the expanded resources
- With client-side (my machine) retrying, all runs were submitted, completed, and published
- The API had ~12 timeout errors uploading resources to the S3 bucket -- all handled by client-side retrying
- The dispatch service experienced 43 502 errors with the API -- all handled by retrying within the dispatch-service
  - 35 posting files
  - 6 posting logs
  - 2 updating size of results
- 1 error message in the API log still has `undefined` in a message. I just tried to fix this.

This is working much better now. I think we'd ideally still try to address the source of these 502 errors because retrying doesn't feel like a robust solution.

**Comment by bilalshaikh42** [comment]
Great! It seems the issue then is that the API is using more memory than was previously available on each node. With some more investigation, we should be able to figure out what is causing the pods to crash that resulting in the retries being needed.

**Comment by bilalshaikh42** [comment]
Looking at https://grafana.api.biosimulations.org/d/nginx/nginx-ingress-controller, it seems the two main causes of error are the HSDS and timeouts when uploading to the storage bucket

**Comment by jonrkarr** [comment]
The 502 errors are between the dispatch service and api.

The storage bucket issues seemed unusually high in my latest test. We can add retrying to help with this. A more robust option is to temporarily store archives to a Google bucket and then upload it to the Uconn bucket when possible, using a queue to manage this i.e. move this into the dispatch queue.

Both the hsds and bucket issues would also be addressed by colacating them with the API as discussed with ion and Mike last week.

**Comment by bilalshaikh42** [comment]
> The 502 errors are between the dispatch service and api.

Yes. I was not clear.I believe most of these are now resolved with the larger node size since we don't have the issue of the API crashing due to running out of memory.  The errors that are happening seem to be due to the API locking up when uploading files/retrying connections to the data service, but I am not completely sure about this. 


> The storage bucket issues seemed unusually high in my latest test

Agreed. It seems at times the response time/speed of the bucket is quite slow. This is also evident when browsing the UI at times.  this would also explain the issues that we have with HSDS (500s when failing to read from bucket, 404 when not finding data that was uploaded to bucket). 

> A more robust option is to temporarily store archives to a Google bucket and then upload it to the Uconn bucket when possible, using a queue to manage this i.e. move this into the dispatch queue.

Storing in a google bucket is quite easy as it just requires a change to the config variables in deployment. Transfering to UConn bucket is also trivial. We can just set up a Cloud Run Function (Googles version of Lamda functions) to trigger whenever a file is uploaded to the google bucket and copy it over to the Uconn bucket. 

The "temporary" aspect is a bit trickier as this requires us to keep track of two separate URLs for the files, depending on where the files are located.  We could use the storage teir [concept](https://cloud.google.com/storage/docs/storage-classes) to manage this, but that is still going to be tricky. The most straightforward solution is to have the API can redirect to the appropriate bucket based on some factor such as age or status.

  I think we can start by switching over to google cloud buckets for file handling at least. We can also move the HSDS over, but this will likely have higher costs over the long run.  I can set the google cloud bucket to copy everything over to the UConn bucket so that we can seamlessly switch between them while we work out a more permanent solution, whether that is hosting kubernetes at UConn, or just switching our storage to the cloud as well

**Comment by bilalshaikh42** [comment]
I will close this issue as its getting a bit long and the main problem should? be resolved. We can open up another issue if we still encounter 502/504s. The 500 is due to hsds/s3 which we can track in #3896
